#+EXPORT_FILE_NAME: ../../learners/setup.md
#+OPTIONS: toc:nil author:nil date:nil num:nil title:nil
#+MACRO: mdheader @@markdown:$1@@

#+begin_export markdown
---
title: "Setup"
---
#+end_export

* Software setup
#+begin_discussion
{{{mdheader(### Details)}}}

We basically require ~pixi~ and ~uv~. For conciseness, we reproduce the most direct
instructions below.

Technically any Python interpreter suffices, here we use ~pixi~ to handle system
dependencies and run tasks, with ~uv~ for managing Python dependencies and
environments.
#+end_discussion

#+begin_spoiler
{{{mdheader(### Windows)}}}

Following along with the ~pixi~ [[https://pixi.prefix.dev/latest/installation/#__tabbed_1_2][instructions upstream here]].

#+begin_src bash
powershell -ExecutionPolicy Bypass -c "irm -useb https://pixi.sh/install.ps1 | iex"
#+end_src

Along with ~uv~ from [[https://docs.astral.sh/uv/getting-started/installation/#__tabbed_1_2][the official installation documentation]].

#+begin_src bash
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
#+end_src

After installation, *restart your terminal* (close and reopen PowerShell or
Command Prompt) so that the PATH changes take effect.

#+end_spoiler

#+begin_spoiler
{{{mdheader(### MacOS and Linux)}}}

Following along with the ~pixi~ [[https://pixi.prefix.dev/latest/installation/#__tabbed_1_1][instructions upstream here]].

#+begin_src bash
curl -fsSL https://pixi.sh/install.sh | sh
#+end_src

Along with ~uv~ [[https://docs.astral.sh/uv/getting-started/installation/#__tabbed_1_1][from the official documentation]].

#+begin_src bash
curl -LsSf https://astral.sh/uv/install.sh | sh
#+end_src

After installation, restart your terminal or run =source ~/.bashrc= (or
=source ~/.zshrc= on macOS) for the PATH changes to take effect.

#+end_spoiler

* Verifying the installation

After installing both tools, open a *new* terminal and run the following commands
to confirm everything is working:

#+begin_src bash
pixi --version
uv --version
#+end_src

You should see version numbers printed for both tools. If either command is not
found, check that the installation directories are on your =PATH= and restart
your terminal.

Additionally, verify that =git= is available:

#+begin_src bash
git --version
#+end_src

If =git= is not installed, follow the [[https://git-scm.com/downloads][official installation instructions]] for your
platform, or install it via =pixi=:

#+begin_src bash
pixi global install git
#+end_src

* Accounts required
To finalize publishing to an index [fn:: Making the code widely available over the net] we need:
- A Git instance in the cloud :: Any of Github, Gitlab, Sourcehut etc. would work, [[https://docs.github.com/en/get-started/start-your-journey/creating-an-account-on-github][Github is recommended]].
- An index account :: For the tutorial [[https://test.pypi.org/account/register/][Test PyPI]] will suffice, for production, an account [[https://pypi.org/account/register/][on PyPI]] would be required as well.

#+begin_checklist

- [ ] I have =pixi= installed and =pixi --version= prints a version number
- [ ] I have =uv= installed and =uv --version= prints a version number
- [ ] I have =git= installed and =git --version= prints a version number
- [ ] I have an account on a Git server (e.g., GitHub)
- [ ] I have an account on [[https://test.pypi.org/account/register/][Test PyPI]]

#+end_checklist

* Optional: Editor setup

Any text editor will work for this lesson. If you do not have a preference, we
suggest [[https://code.visualstudio.com/][VS Code]] with the [[https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff][Ruff extension]] for integrated linting and formatting.

Learners comfortable with the terminal can use any editor they prefer (=vim=,
=emacs=, =nano=, etc.).

# Local Variables:
# eval: (add-hook 'after-save-hook 'export-as-workbench-md nil t)
# End:
